version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - isort *.py
    - black *.py
  lint:
    cmds:
    - pylint *.py
    - mypy --ignore-missing-imports *.py
  default:
    cmds:
    - task: format
    - task: lint