version: '3'

tasks:
  format:
    cmds:
    - deno fmt README.md
    - isort build.py
    - black build.py
  lint:
    cmds:
    - pylint build.py
    - mypy --ignore-missing-imports build.py
  default:
    cmds:
    - task: format
    - task: lint